### ISSUE TITLE
Global marks only remember file, not cursor position

### ISSUE THREAD

**Issue by rasmusq** [BartSte/nvim-project-marks#1]
### Description
There is a problem where performing a certain set of actions makes it so the cursor is teleported to the wrong place, but in the right file when teleporting to a global mark.
Oddly enough, it seems to work fine when you go to the mark via the Telescope selector (builtin.marks).

### Expected behaviour
Going to a global mark using `'N` goes to the file and line on which the mark was created.
### Actual behaviour
Going to a global mark using `'N` goes to the file on which the mark was created but to the line on which the most recent deletion of a mark happened.
This happens unless no mark has been deleted in that file. 

### Steps to reproduce
1. Open NeoVim in folder __x__ with the `nvim` command
2. Open file __a__
3. Create a new mark __M__ on a random line
4. Create a new mark __N__ on another line that is different from the line you chose for __M__
5. Move the cursor to a new, third, line
6. Delete mark __M__
7. Use the `'N` command to go to mark __N__

This action should teleport you to the third line you chose instead of the expected line marked __N__.
Going to another file in the same folder and typing `'N` should teleport to the file, but to the same wrong line.

### More info
NeoVim version:
```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1699392533
```
Plugin version:
```
branch main
commit d69997f
```
Plugin manager:
```
url     https://github.com/folke/lazy.nvim
version 10.15.1
tag     stable
branch  main
commit  9658486
```
System:
```
# System Details Report
---

## Report details
- **Date generated:**                              2023-11-10 20:38:12

## Hardware Information:
- **Hardware Model:**                              Gigabyte Technology Co., Ltd. B550 AORUS ELITE V2
- **Memory:**                                      32,0 GiB
- **Processor:**                                   AMD Ryzen™ 5 5600X × 12
- **Graphics:**                                    AMD Radeon™ RX 6800 XT
- **Disk Capacity:**                               1,0 TB

## Software Information:
- **Firmware Version:**                            FB
- **OS Name:**                                     Arch Linux
- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.1
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.1-arch1-1
```
### Minimal config
A barebones lazy.nvim setup with this as the only plugin:
```
return {
    {
        "BartSte/nvim-project-marks",
        lazy = false,
        config = function()
            require("projectmarks").setup({})
        end,
    },
}
```

**Comment by BartSte** [comment]
@rasmusq thanks for your interest in this plugin.

As stated in the readme, wouldn't the expected behaviour be:

> After jumping to a mark, jump to the last cursor position in that file. That's it, nothing more.

So no jump is made to the file mark, instead the cursor jumps to the last position in the file. 

Does this help?

**Comment by rasmusq** [comment]
Hi @BartSte.
First of all, thank you for making this plugin! 
It is truly a necessary feature making the mark functionality actually useful in NeoVim. I don't know if the marks feature would be usable for me if it didn't exist.
I would argue that its flexibility and proximity to the native implementation makes it a better tool than Harpoon.

That does help with my understanding.
I must have read the point wrong initially.

After reading more into it, I now understand my confusion.
When going to a global mark __A__, it runs the motion `'A'"`.
The `"` mark updates every time the buffer is exited as expected.
What I didn't expect is that it also updates when deleting a mark.
That has got to be a quirk of NeoVim or something.

So it is probably working as expected, sorry for the ping!

I might see if I can change the plugin to only do what you write in your first point:
- "Set marks that only a apply to a specific project".

So jumping to global marks happens as it does in vanilla NeoVim.

Thank you again for a great plugin and for the quick response. I hope it gains some traction.

### Edit 1
Seems like it is a very easy change in the code, so I will just post it here if others stumble upon this. You just have to comment these three lines in `projectmarks.lua`:
```
---@param symbol string
local function _jump_with(symbol)
  local mark = vim.fn.nr2char(vim.fn.getchar())
  local command = symbol .. mark

  -- if mark == string.upper(mark) then
  --   command = command .. symbol .. '"'
  -- end
  vim.api.nvim_feedkeys(command, "n", false)
end
```
An option to disable this jumping, of course, is not in the initial goals of the project, so I do not expect it to be an official change, however...

### Edit 2
I have made a local branch for myself with an option to disable the jumping to `"`. 
If you want to have a look at my (very small) commit or use it in the repo, I can publish it as a feature suggestion.

**Comment by BartSte** [comment]
I think ik you set `mappings = false` in your config, you will gat the behaviour you want, i.e., the vanilla vim behaviour while you marks are still stored in the local shada file.

**Comment by rasmusq** [comment]
Well, I just can't seem to understand any of the features of this plugin. Of course that is the setting that does that!
Thank you for your patience.
I don't think the time I spent yesterday was for nothing, as I got introduced to how Neovim plugins work.

Closing the issue...
