### ISSUE TITLE
it doesn't work?

### ISSUE THREAD

**Issue by Arrow-x** [BartSte/nvim-project-marks#2]
Doesn't pick the nvim.The shada file is at the root of a git project file and uses the global one instead, sometimes the local shada file picks up some data, but not the global marks.
I tried it on a clean neovim 9.4-2 on Arch Linux with Lazy.nvim using the default configuration

**Comment by BartSte** [comment]
Hey @Arrow-x,

The plugin works fine for me. I use the same setup, so that's not the issue. 

- Did you use the default configuration?
- Did you enable lazy loading somehow? 
- Did you create a file named 'nvim.shada' at the root of your repo?
- Can you confirm the issue still persist when you use a minimal config (only use this plugin). Maybee some other plugin you use conflicts with the shada file.

**Comment by Arrow-x** [comment]
Yes to all, here is the minimal config that I used (cleared the cash the state and share folders)
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	'BartSte/nvim-project-marks',
	lazy = false,
	config = function()
		require('projectmarks').setup({})
	end

})
```
The global shada file keeps getting picked rather than the local one, resulting in the marks to be accessible from other repos, or it copies it over to the global one

**Comment by Arrow-x** [comment]
Ah! So I was changing the repos by opening the directory (`nvim ~/somedir`) this way Neovim will pick up the global shada, no matter if `somedir` have a `nvim.shada` or not. 
Only when a file is open that the plugin activate (like if I do `nvim ~/somedif/somefile` and there is a a nvim.shada in the dir).
Switching to another directory without closing, it will not pick the shada there and just keeps the one already loaded.

**Comment by BartSte** [comment]
So it works now for you? I gues my description is the "Usage" part of the README is not very clear. I will update it. In short, 
- the pluging will search for a `nvim.shada` file at your current working directory.
- If none is found, it will tranverse upward your path untill it finds one.
- If none is found, the global shada file is found.

So when you open a file at: `~/somedir/somefile.lua` it will search for a `nvim.shada` file at `~`, as this is the current working directory.

**Comment by Arrow-x** [comment]
if I do `~/somedir/somefile.lua` it WILL find the `nvim.shada` in `somedir` though?

**Comment by BartSte** [comment]
No. The idea is as follows, for example:

- You have your projects stored in the directory: `~/code`
- Lets say you have the following projects:
  - `~/code/project_1/file.lua`
  - `~/code/project_2/file.lua`
- For each project you will have 'nvim.shada` file, like so: 
  - `~/code/project_1/nvim.shada`
  - `~/code/project_2/nvim.shada`
- When you cd into `~/code/project_1` and open `file.lua` in Neovim, 
  the `~/code/project_1/nvim.shada` will be used.
- When you cd into `~/code/project_2` and open `file.lua` in Neovim, 
  the `~/code/project_2/nvim.shada` will be used.
- When you cd into `~` and open `~/code/project_1/file.lua` in Neovim, 
  the global shada will be used as there is no shada file in `~`.

**Comment by Arrow-x** [comment]
I am closing this issue since it seems that the plugin is working as intended

**Comment by Arrow-x** [comment]
Another question if you may?
Neovim will not pick the local `nvim.shada` when you `nvim .` in the directory you want that have a shada file? Only when you open a buffer?

**Comment by BartSte** [comment]
I do not fully understand your question. But I'll try to answer it. 

It should not matter if you open a directory, or a buffer. The plugin will load the shada file that is in your current working directory.
